# Generated by Django 3.1.7 on 2021-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_left', models.IntegerField()),
                ('front_right', models.IntegerField()),
                ('back_right', models.IntegerField()),
                ('co', models.IntegerField()),
            ],
        ),
    ]
