# Generated by Django 3.2.5 on 2021-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_cardata_back_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardataRecord',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('front_left', models.IntegerField()),
                ('front_right', models.IntegerField()),
                ('back_left', models.IntegerField()),
                ('back_right', models.IntegerField()),
                ('co', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cardata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
